- hosts: all
  tasks:
    - name: Copy Artifact
      become: True
      copy:
        src: main
        dest: /opt/main
        mode: o+rwx
    - name: Create a service for app
      become: True
      copy:
        src: main.service
        dest: 
          /etc/systemd/system/main.service
    - name: Start service
      become: True
      ansible.builtin.systemd:
        name: main.service
        daemon_reload: true
        state: started
